### ISSUE TITLE
no matches for kind "Cortex" in version "cortex.opstrace.io/v1alpha1"

### ISSUE THREAD

**Issue by nikhil-nomula** [opstrace/cortex-operator#16]
Following readme to deploy cortex operatoer in GKE and I get the following eror 

```
error: unable to recognize "cortex_operator_test.yaml": no matches for kind "Cortex" in version "cortex.opstrace.io/v1alpha1"
```

What could cause this, my yaml looks like this 

```
apiVersion: cortex.opstrace.io/v1alpha1
kind: Cortex
metadata:
  name: cortex-jd-operator
spec:
  image: "cortexproject/cortex:v1.9.0"
  config:
    server:
      grpc_server_max_recv_msg_size: 41943040
      grpc_server_max_send_msg_size: 41943040
    memberlist:
      max_join_backoff: 1m
      max_join_retries: 20
      min_join_backoff: 1s
    query_range:
      split_queries_by_interval: 24h
    limits:
      compactor_blocks_retention_period: 192h
      ingestion_rate: 100000
      ingestion_rate_strategy: local
      ingestion_burst_size: 200000
      max_global_series_per_user: 10000000
      max_series_per_user: 5000000
      accept_ha_samples: true
      ha_cluster_label: prometheus
      ha_replica_label: prometheus_replica
      ruler_tenant_shard_size: 3
    ingester:
      lifecycler:
        join_after: 30s
        observe_period: 30s
        num_tokens: 512
    blocks_storage:
      tsdb:
        retention_period: 6h
      backend: gcs
      gcs:
        # https://cortexmetrics.io/docs/configuration/configuration-file/#blocks_storage_config
        # TODO: Pass in bucket name
        bucket_name: cortex-data
    configs:
      database:
        # TODO: Do we need this database or can we skip this? 
        # https://cortexmetrics.io/docs/configuration/configuration-file/#configs_config
        # URI where the database can be found (for dev you can use memory://)
        # CLI flag: -configs.database.uri
        uri: https://someuri.com
        # Path where the database migration files can be found
        # CLI flag: -configs.database.migrations-dir
        migrations_dir: /migrations
    alertmanager_storage:
      backend: gcs
      # TODO: Pass in bucket name 
      # https://cortexmetrics.io/docs/configuration/configuration-file/#alertmanager_config
      gcs:
        bucket_name: cortex-config
    ruler_storage:
      backend: gcs
      # TODO: Pass in bucket name 
      # https://cortexmetrics.io/docs/configuration/configuration-file/#ruler_config
      gcs:
        bucket_name: cortex-config
```
